version: '3'

services:
  db:
    image: frodenas/couchdb:1.6
    volumes:
      - ./data:/data
    environment:
      COUCHDB_USERNAME: couch
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}

  accumulator:
    image: arvindsv/json-accumulator:1.1.2
    depends_on:
      - db
    environment:
      RACK_ENV: production
      COUCHDB_USERNAME: couch
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    ports:
      - "4567:4567"
